apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: enterprise-prod

spec:
  replicas: 3

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
      - name: order-service
        image: mandalakodandarao/order-service:IMAGE_TAG

        ports:
        - containerPort: 8080
